# Generated by Django 3.0.7 on 2020-06-10 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='course',
            new_name='CourseRegistration',
        ),
    ]
