# Generated by Django 3.0.7 on 2020-06-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcards',
            name='flash_course',
            field=models.CharField(choices=[('sciences', 'sciences'), ('languages', 'languages'), ('religious', 'religious')], max_length=40),
        ),
    ]
