# Generated by Django 3.0.7 on 2020-06-10 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_auto_20200610_1042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseRegistration',
            new_name='Courses',
        ),
        migrations.AddField(
            model_name='flashcards',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
